#!/usr/bin/env python3
"""
Improved ML Analysis Script for Trust Prediction.
"""

import json
import logging
import warnings
from dataclasses import dataclass
from math import sqrt
from pathlib import Path
from typing import Any, Dict, List, Optional

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Hardware Detection
try:
    import torch

    GPU_AVAILABLE = torch.cuda.is_available()
except ImportError:
    GPU_AVAILABLE = False
    warnings.warn("PyTorch not found; GPU detection disabled. Models will default to CPU.")

# Optional imports with error handling
try:
    import shap

    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False
    warnings.warn("SHAP not available - feature explanations will be skipped")

try:
    from catboost import CatBoostRegressor

    CATBOOST_AVAILABLE = True
except ImportError:
    CATBOOST_AVAILABLE = False

try:
    import xgboost as xgb

    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False

try:
    import lightgbm as lgb

    LIGHTGBM_AVAILABLE = True
except ImportError:
    LIGHTGBM_AVAILABLE = False

try:
    from tabpfn import TabPFNRegressor
    from tabpfn.model_loading import save_fitted_tabpfn_model

    TABPFN_AVAILABLE = True
except ImportError:
    TABPFN_AVAILABLE = False

# Setup Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# Suppress harmless warnings generated by model evaluators
warnings.filterwarnings("ignore", message="X does not have valid feature names")
warnings.filterwarnings(
    "ignore",
    message="X has feature names, but RandomForestRegressor was fitted without feature names",
)
warnings.filterwarnings("ignore", category=UserWarning, module="xgboost")


@dataclass
class Config:
    """Configuration class for the ML analysis."""

    data_path: Path = Path("data") / "all_combined_prepared_with_demographics.xlsx"
    results_path: Path = Path("results") / "ML-Approaches"
    sheet_name: str = "Sheet1"
    test_size: float = 0.2
    random_state: int = 42

    # Number of bootstrap resamples for CatBoost error bars
    bootstrap_n: int = 20

    numerical_features: List[str] = None
    categorical_features: List[str] = None
    target_column: str = "trust"

    def __post_init__(self):
        if self.numerical_features is None:
            self.numerical_features = ["mIoU", "License", "Age"]
        if self.categorical_features is None:
            self.categorical_features = [
                "SCENARIO",
                "INTRODUCTION",
                "Gender",
                "Education",
                "Job",
                "DrivingFrequency",
                "Distance",
            ]
        self.results_path.mkdir(parents=True, exist_ok=True)


class DataProcessor:
    """Handles data loading, validation, and pipeline preprocessing construction."""

    def __init__(self, config: Config):
        self.config = config

    def get_label_mappings(self) -> Dict[str, Dict[str, str]]:
        return {
            "Gender": {"A1": "F", "A2": "M", "A3": "non-binary", "A4": "Prefer not to tell"},
            "Education": {
                "A1": "Secondary School",
                "A2": "Middle School",
                "A3": "High School",
                "A4": "College",
                "A5": "Vocational training",
            },
            "Job": {
                "A1": "Student (school)",
                "A2": "Student (college)",
                "A3": "Employee",
                "A4": "Self-employed",
                "A5": "Jobseeker",
                "A6": "Other",
            },
            "DrivingFrequency": {
                "A1": "Daily",
                "A2": "On working days",
                "A3": "3-4 times a week",
                "A4": "1 time a week",
                "A5": "1-3 times a month",
                "A6": "less than 1 time a month",
            },
            "Distance": {
                "A1": "less than 7.000km",
                "A2": "7.000 - 14.999km",
                "A3": "15.000 - 24.999km",
                "A4": "25.000 - 32.999km",
                "A5": "33.000 or more km",
            },
        }

    def get_feature_name_mappings(self) -> Dict[str, str]:
        return {
            "SCENARIO": "Scenario",
            "SCENARIO_NeueMitte": "Scenario: City",
            "SCENARIO_Ueberland": "Scenario: Cross-Country",
            "SCENARIO_Spielstrasse": "Scenario: Walking Speed Zone",
            "INTRODUCTION_boasting": "Introduction: boasting",
            "INTRODUCTION_ambiguous": "Introduction: ambiguous",
            "INTRODUCTION": "Introduction",
            "Gender_M": "Gender: Male",
            "Gender_non-binary": "Gender: non-binary",
            "Education_High School": "Education: High School",
            "Education_Vocational training": "Education: Vocational training",
            "Job_Jobseeker": "Job: Jobseeker",
            "Job_Other": "Job: Other",
            "Job_Self-employed": "Job: Self-employed",
            "Job_Student (college)": "Job: Student (college)",
            "License": "Driving License (years)",
            "DrivingFrequency": "Driving Frequency",
            "DrivingFrequency_1-3 times a month": "Driving Frequency: 1-3/month",
            "DrivingFrequency_3-4 times a week": "Driving Frequency: 3-4/week",
            "DrivingFrequency_Daily": "Driving Frequency: Daily",
            "DrivingFrequency_less than 1 time a month": "Driving Frequency: <1/month",
            "DrivingFrequency_On working days": "Driving Frequency: Working days",
            "Distance": "Distance",
            "Distance_25.000 - 32.999km": "Distance: 25.000 - 32.999km",
            "Distance_7.000 - 14.999km": "Distance: 7.000 - 14.999km",
            "Distance_less than 7.000km": "Distance: <7.000km",
            "Distance_33.000 or more km": "Distance: >=33.000km",
        }

    def load_and_preprocess_data(self) -> pd.DataFrame:
        if not self.config.data_path.exists():
            raise FileNotFoundError(f"Data file not found: {self.config.data_path}")

        df = pd.read_excel(self.config.data_path, sheet_name=self.config.sheet_name)

        required_columns = (
            self.config.numerical_features
            + self.config.categorical_features
            + [self.config.target_column]
        )
        missing_columns = sorted(set(required_columns) - set(df.columns))
        if missing_columns:
            raise ValueError(
                f"Missing required columns in {self.config.data_path}: {missing_columns}"
            )

        before_rows = len(df)
        df = df.dropna(subset=required_columns).copy()
        dropped_rows = before_rows - len(df)
        if dropped_rows > 0:
            logger.info("Dropped %d rows containing missing required fields.", dropped_rows)

        for column, mapping in self.get_label_mappings().items():
            if column in df.columns:
                df[column] = df[column].replace(mapping)

        df[self.config.target_column] = pd.to_numeric(df[self.config.target_column], errors="raise")

        return df

    def get_preprocessor(self) -> ColumnTransformer:
        numeric_transformer = StandardScaler()
        categorical_transformer = OneHotEncoder(
            sparse_output=False,
            drop="first",
            handle_unknown="ignore",
        )
        return ColumnTransformer(
            transformers=[
                ("num", numeric_transformer, self.config.numerical_features),
                ("cat", categorical_transformer, self.config.categorical_features),
            ]
        )


def prepare_categorical_as_string(frame: pd.DataFrame, columns: List[str]) -> pd.DataFrame:
    output = frame.copy()
    for column in columns:
        output[column] = output[column].astype(str)
    return output


# ---------------------------------------------------------------------------
# Error bar helpers
# ---------------------------------------------------------------------------

def get_xgb_importance_std(model: "xgb.XGBRegressor", feature_names: List[str]) -> np.ndarray:
    """Compute per-feature importance std across individual XGBoost trees."""
    df_trees = model.get_booster().trees_to_dataframe()
    splits = df_trees[df_trees["Feature"] != "Leaf"].copy()
    per_tree = (
        splits.groupby(["Tree", "Feature"])["Gain"]
        .sum()
        .unstack(fill_value=0.0)
        .reindex(columns=feature_names, fill_value=0.0)
    )
    return per_tree.std(axis=0).values


def get_lgb_importance_std(model: "lgb.LGBMRegressor", feature_names: List[str]) -> np.ndarray:
    """Compute per-feature importance std across individual LightGBM trees."""
    model_json = model.booster_.dump_model(num_iteration=model.booster_.num_trees())
    trees = model_json.get("tree_info", [])

    feat_index = {f: i for i, f in enumerate(feature_names)}
    n_trees = len(trees)
    per_tree = np.zeros((n_trees, len(feature_names)))

    def walk(node: dict, tree_idx: int) -> None:
        if "split_feature" in node:
            feat_name = feature_names[node["split_feature"]]
            col = feat_index.get(feat_name)
            if col is not None:
                per_tree[tree_idx, col] += node.get("split_gain", 0.0)
            walk(node["left_child"], tree_idx)
            walk(node["right_child"], tree_idx)

    for tree_idx, tree in enumerate(trees):
        walk(tree["tree_structure"], tree_idx)

    return per_tree.std(axis=0)


def get_catboost_importance_std(
    model_params: dict,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    cat_features: List[str],
    n_bootstrap: int = 20,
    random_state: int = 42,
) -> np.ndarray:
    """Compute per-feature importance std for CatBoost via bootstrap resampling."""
    logger.info("Computing CatBoost error bars via %d bootstrap resamples...", n_bootstrap)
    rng = np.random.default_rng(random_state)
    importances = []

    for _ in range(n_bootstrap):
        idx = rng.integers(0, len(X_train), size=len(X_train))
        X_b = X_train.iloc[idx].copy()
        y_b = y_train.iloc[idx]
        X_b = prepare_categorical_as_string(X_b, cat_features)

        params = dict(model_params)
        model = CatBoostRegressor(**params)
        try:
            model.fit(X_b, y_b)
        except Exception as exc:
            if params.get("task_type") == "GPU":
                logger.warning("CatBoost bootstrap GPU fit failed (%s). Falling back to CPU for this sample.", exc)
                params.pop("task_type", None)
                model = CatBoostRegressor(**params)
                model.fit(X_b, y_b)
            else:
                raise

        importances.append(model.get_feature_importance())

    return np.std(importances, axis=0)


def get_tabpfn_quantile_columns(q_preds: Any, quantiles: List[float]) -> List[tuple[float, np.ndarray]]:
    """Return (quantile, predictions_vector) pairs independent of output orientation."""
    values = np.asarray(q_preds)

    if values.ndim == 1:
        if len(quantiles) != 1:
            raise ValueError("TabPFN returned 1D quantile predictions for multiple quantiles.")
        return [(quantiles[0], values)]

    if values.ndim != 2:
        raise ValueError(f"Unexpected TabPFN quantile output shape: {values.shape}")

    if values.shape[1] == len(quantiles):
        return [(q, values[:, i]) for i, q in enumerate(quantiles)]

    if values.shape[0] == len(quantiles):
        return [(q, values[i, :]) for i, q in enumerate(quantiles)]

    raise ValueError(
        f"Cannot align TabPFN quantiles. output_shape={values.shape}, requested_quantiles={len(quantiles)}"
    )


# ---------------------------------------------------------------------------

class ModelEvaluator:
    """Handles pipeline construction, evaluation, and figure generation."""

    def __init__(self, config: Config, data_processor: DataProcessor):
        self.config = config
        self.data_processor = data_processor
        self.feature_name_mappings = data_processor.get_feature_name_mappings()
        self.results: Dict[str, Dict[str, float]] = {}

    def calculate_metrics(self, y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
        mse = mean_squared_error(y_true, y_pred)
        return {
            "mae": float(mean_absolute_error(y_true, y_pred)),
            "mse": float(mse),
            "rmse": float(sqrt(mse)),
            "r2": float(r2_score(y_true, y_pred)),
        }

    def _save_metrics_summary(self) -> None:
        summary_path = self.config.results_path / "model_metrics.json"
        with summary_path.open("w", encoding="utf-8") as handle:
            json.dump(self.results, handle, indent=2, sort_keys=True)

    def plot_feature_importance(
        self,
        model: Any,
        importances: np.ndarray,
        feature_names: List[str],
        metrics: Dict[str, float],
        method_name: str,
        filename: str,
        std: Optional[np.ndarray] = None,
    ) -> None:
        frame = pd.DataFrame({"Feature": feature_names, "Importance": importances})

        if std is None and hasattr(model, "estimators_"):
            std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)
        if std is not None:
            frame["Std"] = std

        frame["Feature"] = frame["Feature"].replace(self.feature_name_mappings)
        frame = frame.sort_values(by="Importance", ascending=False).reset_index(drop=True)

        fig, ax = plt.subplots(figsize=(12, 8))
        colors = sns.color_palette("muted", n_colors=len(frame))
        yerr = frame["Std"].to_numpy() if "Std" in frame.columns else None
        ax.bar(frame["Feature"], frame["Importance"], yerr=yerr, color=colors, capsize=5)

        ax.set_xlabel("")
        ax.set_ylabel("Importance")
        ax.set_title(f"Feature Importances using {method_name}")

        metrics_text = (
            f"MAE: {metrics['mae']:.4f}\n"
            f"MSE: {metrics['mse']:.4f}\n"
            f"RMSE: {metrics['rmse']:.4f}"
        )
        ax.text(
            0.75,
            0.6,
            metrics_text,
            transform=ax.transAxes,
            fontsize=12,
            verticalalignment="bottom",
            bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "edgecolor": "black"},
        )

        plt.xticks(rotation=45, ha="right", fontsize=10)
        plt.tight_layout()
        plt.subplots_adjust(bottom=0.2)
        sns.despine()

        plt.savefig(self.config.results_path / filename, bbox_inches="tight", pad_inches=0)
        plt.close(fig)

    def plot_permutation_importance(
        self,
        model: Any,
        X_test: pd.DataFrame,
        y_test: pd.Series,
        metrics: Dict[str, float],
    ) -> None:
        logger.info("Calculating permutation importances...")

        perm_importance = permutation_importance(
            model,
            X_test.values,
            y_test,
            n_repeats=30,
            random_state=self.config.random_state,
            scoring="neg_mean_absolute_error",
        )

        frame = (
            pd.DataFrame(
                {
                    "Feature": X_test.columns,
                    "Importance": perm_importance.importances_mean,
                    "Std": perm_importance.importances_std,
                }
            )
            .sort_values(by="Importance", ascending=False)
            .reset_index(drop=True)
        )
        frame["Feature"] = frame["Feature"].replace(self.feature_name_mappings)

        fig, ax = plt.subplots(figsize=(12, 8))
        colors = sns.color_palette("muted", n_colors=len(frame))
        ax.barh(frame["Feature"], frame["Importance"], xerr=frame["Std"], color=colors, capsize=5)
        ax.invert_yaxis()

        ax.set_xlabel("Importance (neg_mean_absolute_error)")
        ax.set_ylabel("Features")
        ax.set_title("Permutation Importances")
        sns.despine()

        metrics_text = (
            f"MAE: {metrics['mae']:.4f}\n"
            f"MSE: {metrics['mse']:.4f}\n"
            f"RMSE: {metrics['rmse']:.4f}"
        )
        ax.text(
            0.72,
            0.1,
            metrics_text,
            transform=ax.transAxes,
            fontsize=12,
            verticalalignment="bottom",
            bbox={"boxstyle": "round,pad=0.3", "facecolor": "white", "edgecolor": "black"},
        )

        plt.tight_layout()
        plt.savefig(self.config.results_path / "perm_importances_random_regressor.png", bbox_inches="tight", pad_inches=0)
        plt.close(fig)

    def generate_shap_plots(
        self,
        model: Any,
        X_eval: pd.DataFrame,
        is_lgbm: bool = False,
        filename: str = "enhanced_shap_summary_plot.png",
    ) -> None:
        if not SHAP_AVAILABLE:
            return
        logger.info("Generating SHAP explanations -> %s", filename)

        try:
            explainer = shap.TreeExplainer(model)

            if is_lgbm:
                explanation = explainer(X_eval)
                explanation.feature_names = [
                    self.feature_name_mappings.get(feature, feature)
                    for feature in explanation.feature_names
                ]

                plt.figure(figsize=(10, 8))
                shap.plots.beeswarm(explanation, show=False)
                plt.tight_layout()
                plt.savefig(self.config.results_path / filename, bbox_inches="tight", pad_inches=0)
                plt.close()
            else:
                shap_values = explainer.shap_values(X_eval)
                X_eval_renamed = X_eval.rename(columns=self.feature_name_mappings)

                plt.figure(figsize=(10, 8))
                shap.summary_plot(
                    shap_values,
                    X_eval_renamed,
                    plot_type="bar",
                    cmap=plt.get_cmap("coolwarm"),
                    show=False,
                )
                plt.tight_layout()
                plt.savefig(self.config.results_path / filename, bbox_inches="tight", pad_inches=0)
                plt.close()

        except Exception as exc:
            logger.error("SHAP analysis failed for %s: %s", filename, exc)

    def evaluate_all_models(self, df: pd.DataFrame) -> None:
        X = df[self.config.numerical_features + self.config.categorical_features]
        y = df[self.config.target_column]

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=self.config.test_size,
            random_state=self.config.random_state,
        )
        preprocessor = self.data_processor.get_preprocessor()

        # ------------------------------------------------------------------
        # 1. Random Forest
        # ------------------------------------------------------------------
        logger.info("Training Random Forest...")
        rf_pipeline = Pipeline(
            steps=[
                ("preprocessor", preprocessor),
                ("regressor", RandomForestRegressor(n_estimators=100, random_state=self.config.random_state)),
            ]
        )
        rf_pipeline.fit(X_train, y_train)

        y_pred_rf = rf_pipeline.predict(X_test)
        metrics_rf = self.calculate_metrics(y_test, y_pred_rf)
        self.results["Random Forest"] = metrics_rf

        rf_model = rf_pipeline.named_steps["regressor"]
        fitted_preprocessor = rf_pipeline.named_steps["preprocessor"]
        raw_feature_names = fitted_preprocessor.get_feature_names_out()
        base_feature_names = [name.split("__")[-1] for name in raw_feature_names]

        X_test_transformed = pd.DataFrame(
            fitted_preprocessor.transform(X_test),
            columns=base_feature_names,
            index=X_test.index,
        )

        self.plot_feature_importance(
            rf_model,
            rf_model.feature_importances_,
            base_feature_names,
            metrics_rf,
            "Mean Decrease in Impurity",
            "feature_importance_random_classifier.png",
        )
        self.plot_permutation_importance(rf_model, X_test_transformed, y_test, metrics_rf)
        self.generate_shap_plots(
            rf_model,
            X_test_transformed,
            filename="enhanced_shap_summary_plot.png",
        )

        # ------------------------------------------------------------------
        # 2. CatBoost
        # ------------------------------------------------------------------
        if CATBOOST_AVAILABLE:
            logger.info("Training CatBoost...")
            X_train_cat = prepare_categorical_as_string(X_train, self.config.categorical_features)
            X_test_cat = prepare_categorical_as_string(X_test, self.config.categorical_features)

            cb_params = {
                "cat_features": self.config.categorical_features,
                "random_state": self.config.random_state,
                "verbose": False,
            }
            if GPU_AVAILABLE:
                cb_params["task_type"] = "GPU"

            cb_model = CatBoostRegressor(**cb_params)
            try:
                cb_model.fit(X_train_cat, y_train)
            except Exception as exc:
                if cb_params.get("task_type") == "GPU":
                    logger.warning("CatBoost GPU fit failed (%s). Falling back to CPU...", exc)
                    cb_params.pop("task_type", None)
                    cb_model = CatBoostRegressor(**cb_params)
                    cb_model.fit(X_train_cat, y_train)
                else:
                    raise

            metrics_cb = self.calculate_metrics(y_test, cb_model.predict(X_test_cat))
            self.results["CatBoost"] = metrics_cb

            std_cb = None
            try:
                std_cb = get_catboost_importance_std(
                    model_params=cb_params,
                    X_train=X_train_cat,
                    y_train=y_train,
                    cat_features=self.config.categorical_features,
                    n_bootstrap=self.config.bootstrap_n,
                    random_state=self.config.random_state,
                )
            except Exception as exc:
                logger.warning("CatBoost bootstrap std computation failed: %s", exc)

            self.plot_feature_importance(
                cb_model,
                cb_model.get_feature_importance(),
                X_train.columns.tolist(),
                metrics_cb,
                "CatBoost",
                "feature_importance_catboost.png",
                std=std_cb,
            )
            self.generate_shap_plots(
                cb_model,
                X_test_cat,
                filename="feature_importance_catboost_shap.png",
            )

        # ------------------------------------------------------------------
        # 3. XGBoost
        # ------------------------------------------------------------------
        if XGBOOST_AVAILABLE:
            logger.info("Training XGBoost...")
            X_train_xgb = X_train.copy()
            X_test_xgb = X_test.copy()
            for column in self.config.categorical_features:
                X_train_xgb[column] = X_train_xgb[column].astype("category")
                X_test_xgb[column] = X_test_xgb[column].astype("category")

            xgb_params = {"random_state": self.config.random_state, "enable_categorical": True}
            if GPU_AVAILABLE:
                xgb_params["tree_method"] = "hist"
                xgb_params["device"] = "cuda"

            xgb_model = xgb.XGBRegressor(**xgb_params)
            try:
                xgb_model.fit(X_train_xgb, y_train)
            except Exception as exc:
                logger.warning("XGBoost GPU fit failed (%s). Falling back to CPU...", exc)
                xgb_model = xgb.XGBRegressor(
                    random_state=self.config.random_state,
                    enable_categorical=True,
                )
                xgb_model.fit(X_train_xgb, y_train)

            xgb_model.save_model(self.config.results_path / "your_model.json")
            xgb_model.save_model(Path("your_model.json"))

            metrics_xgb = self.calculate_metrics(y_test, xgb_model.predict(X_test_xgb))
            self.results["XGBoost"] = metrics_xgb

            std_xgb = get_xgb_importance_std(xgb_model, X_train.columns.tolist())

            self.plot_feature_importance(
                xgb_model,
                xgb_model.feature_importances_,
                X_train.columns.tolist(),
                metrics_xgb,
                "XGBoost",
                "feature_importance_xgboost.png",
                std=std_xgb,
            )
            self.generate_shap_plots(
                xgb_model,
                X_test_xgb,
                filename="feature_importance_xgboost_shap.png",
            )

        # ------------------------------------------------------------------
        # 4. LightGBM
        # ------------------------------------------------------------------
        if LIGHTGBM_AVAILABLE:
            logger.info("Training LightGBM...")
            X_train_lgb = X_train.copy()
            X_test_lgb = X_test.copy()
            for column in self.config.categorical_features:
                X_train_lgb[column] = X_train_lgb[column].astype("category")
                X_test_lgb[column] = X_test_lgb[column].astype("category")

            lgb_params = {"random_state": self.config.random_state, "verbose": -1}
            if GPU_AVAILABLE:
                lgb_params["device"] = "gpu"

            lgb_model = lgb.LGBMRegressor(**lgb_params)
            try:
                lgb_model.fit(X_train_lgb, y_train)
            except Exception:
                logger.warning(
                    "LightGBM GPU fit failed (usually missing OpenCL compilation). Falling back to CPU..."
                )
                lgb_model = lgb.LGBMRegressor(random_state=self.config.random_state, verbose=-1)
                lgb_model.fit(X_train_lgb, y_train)

            metrics_lgb = self.calculate_metrics(y_test, lgb_model.predict(X_test_lgb))
            self.results["LightGBM"] = metrics_lgb

            std_lgb = get_lgb_importance_std(lgb_model, X_train.columns.tolist())

            self.plot_feature_importance(
                lgb_model,
                lgb_model.feature_importances_,
                X_train.columns.tolist(),
                metrics_lgb,
                "LightGBM",
                "feature_importance_lightgbm.png",
                std=std_lgb,
            )
            self.generate_shap_plots(
                lgb_model,
                X_test_lgb,
                is_lgbm=True,
                filename="enhanced_shap_summary_plot_lgboost.png",
            )

        # ------------------------------------------------------------------
        # 5. TabPFN
        # ------------------------------------------------------------------
        if TABPFN_AVAILABLE:
            X_train_tab = preprocessor.fit_transform(X_train)
            X_test_tab = preprocessor.transform(X_test)

            logger.info(
                "Training TabPFN on 100%% of the training data (%d rows) without subsampling...",
                len(X_train_tab),
            )

            tabpfn_params = {
                "ignore_pretraining_limits": True,
                "device": "cuda" if GPU_AVAILABLE else "cpu",
            }
            reg = TabPFNRegressor(**tabpfn_params)
            try:
                reg.fit(X_train_tab, y_train.values)
            except Exception as exc:
                if tabpfn_params["device"] == "cuda":
                    logger.warning("TabPFN GPU fit failed (%s). Falling back to CPU...", exc)
                    reg = TabPFNRegressor(ignore_pretraining_limits=True, device="cpu")
                    reg.fit(X_train_tab, y_train.values)
                else:
                    raise

            save_fitted_tabpfn_model(reg, self.config.results_path / "fact-av.tabpfn_fit")

            preds = reg.predict(X_test_tab)
            metrics_tab = self.calculate_metrics(y_test, preds)
            self.results["TabPFN"] = metrics_tab

            results_txt = [
                f"Mean Squared Error (MSE): {metrics_tab['mse']}",
                f"Mean Absolute Error (MAE): {metrics_tab['mae']}",
                f"R-squared (R^2): {metrics_tab['r2']}",
            ]

            quantiles = [0.25, 0.5, 0.75]
            q_preds = reg.predict(X_test_tab, output_type="quantiles", quantiles=quantiles)
            for quantile, quantile_preds in get_tabpfn_quantile_columns(q_preds, quantiles):
                results_txt.append(f"Quantile {quantile} MAE: {mean_absolute_error(y_test, quantile_preds)}")

            mode_preds = reg.predict(X_test_tab, output_type="mode")
            results_txt.append(f"Mode MAE: {mean_absolute_error(y_test, mode_preds)}")

            with (self.config.results_path / "results_tabpfnregressor.txt").open("w", encoding="utf-8") as handle:
                handle.write("\n".join(results_txt))

        self._save_metrics_summary()


def main() -> None:
    if GPU_AVAILABLE:
        logger.info("Nvidia GPU detected. Supported models will try hardware acceleration.")
    else:
        logger.info("No compatible GPU detected. Running on CPU.")

    optional_status = {
        "SHAP": SHAP_AVAILABLE,
        "CatBoost": CATBOOST_AVAILABLE,
        "XGBoost": XGBOOST_AVAILABLE,
        "LightGBM": LIGHTGBM_AVAILABLE,
        "TabPFN": TABPFN_AVAILABLE,
    }
    unavailable = [name for name, available in optional_status.items() if not available]
    if unavailable:
        logger.info("Optional dependencies not available: %s", ", ".join(unavailable))

    config = Config()
    np.random.seed(config.random_state)

    data_processor = DataProcessor(config)
    df = data_processor.load_and_preprocess_data()

    evaluator = ModelEvaluator(config, data_processor)
    evaluator.evaluate_all_models(df)

    logger.info("Script execution complete. Results generated in %s", config.results_path)


if __name__ == "__main__":
    plt.style.use("seaborn-v0_8-whitegrid")
    main()
