#!/usr/bin/env python3
"""
Improved ML Analysis Script for Trust Prediction
(Fixes TabPFN PyTorch Bug, XGBoost Warnings, GPU Support, & Generates all Original Figures)
(v2: Adds proper error bars for CatBoost via bootstrap, XGBoost/LightGBM via per-tree extraction)
"""

import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import logging
import warnings
from math import sqrt
from typing import Dict, List, Any, Optional
from dataclasses import dataclass

# ML imports
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, make_scorer
from sklearn.inspection import permutation_importance
from sklearn.cluster import DBSCAN

# Hardware Detection
try:
    import torch
    GPU_AVAILABLE = torch.cuda.is_available()
except ImportError:
    GPU_AVAILABLE = False
    warnings.warn("PyTorch not found; GPU detection disabled. Models will default to CPU.")

# Optional imports with error handling
try:
    import shap
    SHAP_AVAILABLE = True
except ImportError:
    SHAP_AVAILABLE = False
    warnings.warn("SHAP not available - feature explanations will be skipped")

try:
    from catboost import CatBoostRegressor
    CATBOOST_AVAILABLE = True
except ImportError:
    CATBOOST_AVAILABLE = False

try:
    import xgboost as xgb
    XGBOOST_AVAILABLE = True
except ImportError:
    XGBOOST_AVAILABLE = False

try:
    import lightgbm as lgb
    LIGHTGBM_AVAILABLE = True
except ImportError:
    LIGHTGBM_AVAILABLE = False

try:
    from tabpfn import TabPFNRegressor
    from tabpfn.model_loading import save_fitted_tabpfn_model
    TABPFN_AVAILABLE = True
except ImportError:
    TABPFN_AVAILABLE = False

# Setup Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Suppress harmless warnings generated by model evaluators
warnings.filterwarnings("ignore", message="X does not have valid feature names")
warnings.filterwarnings("ignore", message="X has feature names, but RandomForestRegressor was fitted without feature names")
warnings.filterwarnings("ignore", category=UserWarning, module="xgboost")


@dataclass
class Config:
    """Configuration class for the ML analysis"""
    data_path: Path = Path("data") / "all_combined_prepared_with_demographics.xlsx"
    results_path: Path = Path("results") / "ML-Approaches"
    sheet_name: str = "Sheet1"
    test_size: float = 0.2
    random_state: int = 42

    # Number of bootstrap resamples for CatBoost error bars
    bootstrap_n: int = 20

    numerical_features: List[str] = None
    categorical_features: List[str] = None
    target_column: str = "trust"

    def __post_init__(self):
        if self.numerical_features is None:
            self.numerical_features = ['mIoU', 'License', 'Age']
        if self.categorical_features is None:
            self.categorical_features = ['SCENARIO', 'INTRODUCTION', 'Gender', 'Education', 'Job', 'DrivingFrequency', 'Distance']
        self.results_path.mkdir(parents=True, exist_ok=True)


class DataProcessor:
    """Handles data loading, validation, and pipeline preprocessing construction"""

    def __init__(self, config: Config):
        self.config = config

    def get_label_mappings(self) -> Dict[str, Dict[str, str]]:
        return {
            'Gender': {"A1": "F", "A2": "M", "A3": "non-binary", "A4": "Prefer not to tell"},
            'Education': {"A1": "Secondary School", "A2": "Middle School", "A3": "High School", "A4": "College", "A5": "Vocational training"},
            'Job': {"A1": "Student (school)", "A2": "Student (college)", "A3": "Employee", "A4": "Self-employed", "A5": "Jobseeker", "A6": "Other"},
            'DrivingFrequency': {"A1": "Daily", "A2": "On working days", "A3": "3-4 times a week", "A4": "1 time a week", "A5": "1-3 times a month", "A6": "less than 1 time a month"},
            'Distance': {"A1": "less than 7.000km", "A2": "7.000 - 14.999km", "A3": "15.000 - 24.999km", "A4": "25.000 - 32.999km", "A5": "33.000 or more km"}
        }

    def get_feature_name_mappings(self) -> Dict[str, str]:
        return {
            'SCENARIO': 'Scenario', 'SCENARIO_NeueMitte': 'Scenario: City', 'SCENARIO_Ueberland': 'Scenario: Cross-Country',
            'SCENARIO_Spielstrasse': 'Scenario: Walking Speed Zone', 'INTRODUCTION_boasting': 'Introduction: boasting',
            'INTRODUCTION_ambiguous': 'Introduction: ambiguous', 'INTRODUCTION': 'Introduction',
            'Gender_M': 'Gender: Male', 'Gender_non-binary': 'Gender: non-binary',
            'Education_High School': 'Education: High School', 'Education_Vocational training': 'Education: Vocational training',
            'Job_Jobseeker': 'Job: Jobseeker', 'Job_Other': 'Job: Other', 'Job_Self-employed': 'Job: Self-employed',
            'Job_Student (college)': 'Job: Student (college)', 'License': 'Driving License (years)',
            'DrivingFrequency': 'Driving Frequency', 'DrivingFrequency_1-3 times a month': 'Driving Frequency: 1-3/month',
            'DrivingFrequency_3-4 times a week': 'Driving Frequency: 3-4/week', 'DrivingFrequency_Daily': 'Driving Frequency: Daily',
            'DrivingFrequency_less than 1 time a month': 'Driving Frequency: <1/month', 'DrivingFrequency_On working days': 'Driving Frequency: Working days',
            'Distance': 'Distance', 'Distance_25.000 - 32.999km': 'Distance: 25.000 - 32.999km', 'Distance_7.000 - 14.999km': 'Distance: 7.000 - 14.999km',
            'Distance_less than 7.000km': 'Distance: <7.000km', 'Distance_33.000 or more km': 'Distance: >=30.000km'
        }

    def load_and_preprocess_data(self) -> pd.DataFrame:
        if not self.config.data_path.exists():
            raise FileNotFoundError(f"Data file not found: {self.config.data_path}")

        df = pd.read_excel(self.config.data_path, sheet_name=self.config.sheet_name)
        df.dropna(inplace=True)

        for column, mapping in self.get_label_mappings().items():
            if column in df.columns:
                df[column] = df[column].replace(mapping)

        return df

    def get_preprocessor(self) -> ColumnTransformer:
        numeric_transformer = StandardScaler()
        categorical_transformer = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')
        return ColumnTransformer(transformers=[
            ('num', numeric_transformer, self.config.numerical_features),
            ('cat', categorical_transformer, self.config.categorical_features)
        ])


# ---------------------------------------------------------------------------
# Error bar helpers
# ---------------------------------------------------------------------------

def get_xgb_importance_std(model: "xgb.XGBRegressor", feature_names: List[str]) -> np.ndarray:
    """
    Compute per-feature importance std across individual XGBoost trees.
    Uses the booster's tree dataframe — no retraining required.
    """
    df_trees = model.get_booster().trees_to_dataframe()
    # Keep only split nodes (leaves have Feature == 'Leaf')
    splits = df_trees[df_trees['Feature'] != 'Leaf'].copy()
    # Gain is already stored per node; sum per (tree, feature)
    per_tree = (
        splits.groupby(['Tree', 'Feature'])['Gain']
        .sum()
        .unstack(fill_value=0.0)
        .reindex(columns=feature_names, fill_value=0.0)
    )
    return per_tree.std(axis=0).values


def get_lgb_importance_std(model: "lgb.LGBMRegressor", feature_names: List[str]) -> np.ndarray:
    """
    Compute per-feature importance std across individual LightGBM trees.
    Walks each tree's JSON structure to accumulate split_gain per feature.
    No retraining required.
    """
    model_json = model.booster_.dump_model(num_iteration=model.booster_.num_trees())
    trees = model_json.get('tree_info', [])

    feat_index = {f: i for i, f in enumerate(feature_names)}
    n_trees = len(trees)
    per_tree = np.zeros((n_trees, len(feature_names)))

    def walk(node: dict, tree_idx: int) -> None:
        if 'split_feature' in node:
            feat_name = feature_names[node['split_feature']]
            col = feat_index.get(feat_name, None)
            if col is not None:
                per_tree[tree_idx, col] += node.get('split_gain', 0.0)
            walk(node['left_child'], tree_idx)
            walk(node['right_child'], tree_idx)

    for t_idx, tree in enumerate(trees):
        walk(tree['tree_structure'], t_idx)

    return per_tree.std(axis=0)


def get_catboost_importance_std(
    model_params: dict,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    feature_names: List[str],
    cat_features: List[str],
    n_bootstrap: int = 20,
    random_state: int = 42,
) -> np.ndarray:
    """
    Compute per-feature importance std for CatBoost via bootstrap resampling.
    Trains `n_bootstrap` lightweight models on resampled data and measures
    the variance in their feature importances.
    """
    logger.info(f"Computing CatBoost error bars via {n_bootstrap} bootstrap resamples...")
    rng = np.random.default_rng(random_state)
    importances = []

    for i in range(n_bootstrap):
        idx = rng.integers(0, len(X_train), size=len(X_train))
        X_b = X_train.iloc[idx].copy()
        y_b = y_train.iloc[idx]

        # Ensure categoricals are strings
        for col in cat_features:
            X_b[col] = X_b[col].astype(str)

        m = CatBoostRegressor(**model_params)
        m.fit(X_b, y_b)
        importances.append(m.get_feature_importance())

    return np.std(importances, axis=0)


# ---------------------------------------------------------------------------

class ModelEvaluator:
    """Handles pipeline construction, evaluation, and original figure generation"""

    def __init__(self, config: Config, data_processor: DataProcessor):
        self.config = config
        self.data_processor = data_processor
        self.feature_name_mappings = data_processor.get_feature_name_mappings()
        self.results = {}

    def calculate_metrics(self, y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
        mse = mean_squared_error(y_true, y_pred)
        return {
            'mae': mean_absolute_error(y_true, y_pred),
            'mse': mse,
            'rmse': sqrt(mse),
            'r2': r2_score(y_true, y_pred)
        }

    def plot_feature_importance(
        self,
        model: Any,
        importances: np.ndarray,
        feature_names: List[str],
        metrics: Dict[str, float],
        method_name: str,
        filename: str,
        std: Optional[np.ndarray] = None,   # <-- explicit std passed in
    ) -> None:
        sns.set(style="whitegrid")
        importance_df = pd.Series(importances, index=feature_names)
        importance_df.index = importance_df.index.to_series().replace(self.feature_name_mappings)

        plt.figure(figsize=(12, 8))
        sns.barplot(x=importance_df.index, y=importance_df.values, hue=importance_df.index, palette="muted", legend=False)

        # Resolve std: explicit > Random Forest estimators_ > None (no error bars)
        if std is None and hasattr(model, 'estimators_'):
            std = np.std([tree.feature_importances_ for tree in model.estimators_], axis=0)

        if std is not None:
            plt.errorbar(
                x=np.arange(len(importance_df)),
                y=importance_df.values,
                yerr=std,
                fmt='none',
                c='black',
                capsize=5,
            )

        plt.xlabel('')
        plt.ylabel('Importance')
        plt.title(f'Feature Importances using {method_name}')

        metrics_text = f"MAE: {metrics['mae']:.4f}\nMSE: {metrics['mse']:.4f}\nRMSE: {metrics['rmse']:.4f}"
        plt.text(0.75, 0.6, metrics_text, transform=plt.gca().transAxes, fontsize=12,
                 verticalalignment='bottom', bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='black'))

        plt.xticks(rotation=45, ha='right', fontsize=10)
        plt.tight_layout()
        plt.subplots_adjust(bottom=0.2)
        sns.despine()

        plt.savefig(self.config.results_path / filename, bbox_inches='tight', pad_inches=0)
        plt.close()

    def plot_permutation_importance(self, model: Any, X_test: pd.DataFrame, y_test: pd.Series, metrics: Dict[str, float]) -> None:
        logger.info("Calculating Permutation Importances...")
        mae_scorer = make_scorer(mean_absolute_error, greater_is_better=False)

        perm_importance = permutation_importance(model, X_test.values, y_test, n_repeats=30, random_state=42, scoring=mae_scorer)

        importance_data = pd.DataFrame({
            'Feature': X_test.columns,
            'Importance': perm_importance.importances_mean,
            'Std': perm_importance.importances_std
        }).sort_values(by='Importance', ascending=False)

        importance_data['Feature'] = importance_data['Feature'].replace(self.feature_name_mappings)

        plt.figure(figsize=(12, 8))
        sns.barplot(x='Importance', y='Feature', data=importance_data, hue="Importance", palette="muted", legend=False)
        plt.errorbar(x=importance_data['Importance'], y=np.arange(len(importance_data)),
                     xerr=importance_data['Std'], fmt='none', c='black', capsize=5)

        plt.xlabel('Importance')
        plt.ylabel('Features')
        plt.title('Permutation Importances using Mean Decrease in Impurity')
        sns.despine()

        metrics_text = f"MAE: {metrics['mae']:.4f}\nMSE: {metrics['mse']:.4f}\nRMSE: {metrics['rmse']:.4f}"
        plt.text(0.75, 0.6, metrics_text, transform=plt.gca().transAxes, fontsize=12,
                 verticalalignment='bottom', bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='black'))

        plt.xticks(rotation=45, ha='right', fontsize=10)
        plt.tight_layout()
        plt.savefig(self.config.results_path / 'perm_importances_random_regressor.png', bbox_inches='tight', pad_inches=0)
        plt.close()

    def generate_shap_plots(self, model: Any, X_eval: pd.DataFrame, is_lgbm: bool = False, filename: str = 'enhanced_shap_summary_plot.png') -> None:
        if not SHAP_AVAILABLE:
            return
        logger.info(f"Generating SHAP explanations -> {filename}")

        try:
            explainer = shap.TreeExplainer(model)

            if is_lgbm:
                explanation = explainer(X_eval)
                explanation.feature_names = [self.feature_name_mappings.get(feat, feat) for feat in explanation.feature_names]

                plt.figure(figsize=(10, 8))
                shap.plots.beeswarm(explanation, show=False)
                plt.tight_layout()
                plt.savefig(self.config.results_path / filename, bbox_inches='tight', pad_inches=0)
                plt.close()
            else:
                shap_values = explainer.shap_values(X_eval)
                X_eval_renamed = X_eval.rename(columns=self.feature_name_mappings)

                plt.figure(figsize=(10, 8))
                shap.summary_plot(shap_values, X_eval_renamed, plot_type="bar", cmap=plt.get_cmap('coolwarm'), show=False)
                plt.tight_layout()
                plt.savefig(self.config.results_path / filename, bbox_inches='tight', pad_inches=0)
                plt.close()

        except Exception as e:
            logger.error(f"SHAP analysis failed for {filename}: {e}")

    def evaluate_all_models(self, df: pd.DataFrame):
        X = df[self.config.numerical_features + self.config.categorical_features]
        y = df[self.config.target_column]

        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=self.config.test_size, random_state=self.config.random_state
        )
        preprocessor = self.data_processor.get_preprocessor()

        # ------------------------------------------------------------------
        # 1. RANDOM FOREST — std from estimators_ (unchanged)
        # ------------------------------------------------------------------
        logger.info("Training Random Forest...")
        rf_pipeline = Pipeline(steps=[
            ('preprocessor', preprocessor),
            ('regressor', RandomForestRegressor(n_estimators=100, random_state=42))
        ])
        rf_pipeline.fit(X_train, y_train)

        y_pred_rf = rf_pipeline.predict(X_test)
        metrics_rf = self.calculate_metrics(y_test, y_pred_rf)
        self.results['Random Forest'] = metrics_rf

        rf_model = rf_pipeline.named_steps['regressor']
        raw_feature_names = preprocessor.get_feature_names_out()
        base_feature_names = [name.split('__')[-1] for name in raw_feature_names]

        X_test_transformed = pd.DataFrame(
            rf_pipeline.named_steps['preprocessor'].transform(X_test),
            columns=base_feature_names
        )

        # std=None → falls back to estimators_ branch inside plot_feature_importance
        self.plot_feature_importance(rf_model, rf_model.feature_importances_, base_feature_names,
                                     metrics_rf, 'Mean Decrease in Impurity',
                                     'feature_importance_random_classifier.png')
        self.plot_permutation_importance(rf_model, X_test_transformed, y_test, metrics_rf)
        self.generate_shap_plots(rf_model, X_test_transformed, filename='enhanced_shap_summary_plot.png')

        # ------------------------------------------------------------------
        # 2. CATBOOST — std via bootstrap resampling
        # ------------------------------------------------------------------
        if CATBOOST_AVAILABLE:
            logger.info("Training CatBoost...")
            X_train_cat, X_test_cat = X_train.copy(), X_test.copy()
            for col in self.config.categorical_features:
                X_train_cat[col] = X_train_cat[col].astype(str)
                X_test_cat[col] = X_test_cat[col].astype(str)

            cb_params = {
                'cat_features': self.config.categorical_features,
                'random_state': 42,
                'verbose': False,
            }
            if GPU_AVAILABLE:
                cb_params['task_type'] = 'GPU'

            cb_model = CatBoostRegressor(**cb_params)
            cb_model.fit(X_train_cat, y_train)

            metrics_cb = self.calculate_metrics(y_test, cb_model.predict(X_test_cat))
            self.results['CatBoost'] = metrics_cb

            # Bootstrap std — uses the same params so results are comparable
            std_cb = get_catboost_importance_std(
                model_params=cb_params,
                X_train=X_train_cat,
                y_train=y_train,
                feature_names=X_train.columns.tolist(),
                cat_features=self.config.categorical_features,
                n_bootstrap=self.config.bootstrap_n,
                random_state=self.config.random_state,
            )

            self.plot_feature_importance(cb_model, cb_model.get_feature_importance(),
                                         X_train.columns.tolist(), metrics_cb,
                                         'CatBoost', 'feature_importance_catboost.png',
                                         std=std_cb)
            self.generate_shap_plots(cb_model, X_test_cat, filename='feature_importance_catboost_shap.png')

        # ------------------------------------------------------------------
        # 3. XGBOOST — std via per-tree gain extraction
        # ------------------------------------------------------------------
        if XGBOOST_AVAILABLE:
            logger.info("Training XGBoost...")
            X_train_xgb, X_test_xgb = X_train.copy(), X_test.copy()
            for col in self.config.categorical_features:
                X_train_xgb[col] = X_train_xgb[col].astype('category')
                X_test_xgb[col] = X_test_xgb[col].astype('category')

            xgb_params = {'random_state': 42, 'enable_categorical': True}
            if GPU_AVAILABLE:
                xgb_params['tree_method'] = 'hist'
                xgb_params['device'] = 'cuda'

            xgb_model = xgb.XGBRegressor(**xgb_params)
            try:
                xgb_model.fit(X_train_xgb, y_train)
            except Exception as e:
                logger.warning(f"XGBoost GPU fit failed ({e}). Falling back to CPU...")
                xgb_model = xgb.XGBRegressor(random_state=42, enable_categorical=True)
                xgb_model.fit(X_train_xgb, y_train)

            xgb_model.save_model(self.config.results_path / 'your_model.json')

            metrics_xgb = self.calculate_metrics(y_test, xgb_model.predict(X_test_xgb))
            self.results['XGBoost'] = metrics_xgb

            # Per-tree std — no retraining needed
            std_xgb = get_xgb_importance_std(xgb_model, X_train.columns.tolist())

            self.plot_feature_importance(xgb_model, xgb_model.feature_importances_,
                                         X_train.columns.tolist(), metrics_xgb,
                                         'XGBoost', 'feature_importance_xgboost.png',
                                         std=std_xgb)
            self.generate_shap_plots(xgb_model, X_test_xgb, filename='feature_importance_xgboost_shap.png')

        # ------------------------------------------------------------------
        # 4. LIGHTGBM — std via per-tree gain extraction
        # ------------------------------------------------------------------
        if LIGHTGBM_AVAILABLE:
            logger.info("Training LightGBM...")
            X_train_lgb, X_test_lgb = X_train.copy(), X_test.copy()
            for col in self.config.categorical_features:
                X_train_lgb[col] = X_train_lgb[col].astype('category')
                X_test_lgb[col] = X_test_lgb[col].astype('category')

            lgb_params = {'random_state': 42, 'verbose': -1}
            if GPU_AVAILABLE:
                lgb_params['device'] = 'gpu'

            lgb_model = lgb.LGBMRegressor(**lgb_params)
            try:
                lgb_model.fit(X_train_lgb, y_train)
            except Exception as e:
                logger.warning(f"LightGBM GPU fit failed (usually missing OpenCL compilation). Falling back to CPU...")
                lgb_model = lgb.LGBMRegressor(random_state=42, verbose=-1)
                lgb_model.fit(X_train_lgb, y_train)

            metrics_lgb = self.calculate_metrics(y_test, lgb_model.predict(X_test_lgb))
            self.results['LightGBM'] = metrics_lgb

            # Per-tree std — no retraining needed
            std_lgb = get_lgb_importance_std(lgb_model, X_train.columns.tolist())

            self.plot_feature_importance(lgb_model, lgb_model.feature_importances_,
                                         X_train.columns.tolist(), metrics_lgb,
                                         'LightGBM', 'feature_importance_lightgbm.png',
                                         std=std_lgb)
            self.generate_shap_plots(lgb_model, X_test_lgb, is_lgbm=True,
                                     filename='enhanced_shap_summary_plot_lgboost.png')

        # ------------------------------------------------------------------
        # 5. TABPFN
        # ------------------------------------------------------------------
        if TABPFN_AVAILABLE:
            X_train_tab = preprocessor.fit_transform(X_train)
            X_test_tab = preprocessor.transform(X_test)

            logger.info(f"Training TabPFN on 100% of the training data ({len(X_train_tab)} rows) without subsampling...")

            tabpfn_params = {'ignore_pretraining_limits': True, 'device': 'cpu'}
            reg = TabPFNRegressor(**tabpfn_params)
            reg.fit(X_train_tab, y_train.values)
            save_fitted_tabpfn_model(reg, self.config.results_path / "fact-av.tabpfn_fit")

            preds = reg.predict(X_test_tab)
            metrics_tab = self.calculate_metrics(y_test, preds)
            self.results['TabPFN'] = metrics_tab

            results_txt = [
                f"Mean Squared Error (MSE): {metrics_tab['mse']}",
                f"Mean Absolute Error (MAE): {metrics_tab['mae']}",
                f"R-squared (R^2): {metrics_tab['r2']}"
            ]

            quantiles = [0.25, 0.5, 0.75]
            q_preds = reg.predict(X_test_tab, output_type="quantiles", quantiles=quantiles)
            for q, q_p in zip(quantiles, q_preds):
                results_txt.append(f"Quantile {q} MAE: {mean_absolute_error(y_test, q_p)}")

            mode_preds = reg.predict(X_test_tab, output_type="mode")
            results_txt.append(f"Mode MAE: {mean_absolute_error(y_test, mode_preds)}")

            with open(self.config.results_path / 'results_tabpfnregressor.txt', "w") as file:
                file.write("\n".join(results_txt))


def main():
    if GPU_AVAILABLE:
        logger.info("Nvidia GPU Detected! Supported models will use hardware acceleration.")
    else:
        logger.info("No compatible GPU detected. Running strictly on CPU.")

    config = Config()
    data_processor = DataProcessor(config)
    df = data_processor.load_and_preprocess_data()

    # ML Pipelines
    evaluator = ModelEvaluator(config, data_processor)
    evaluator.evaluate_all_models(df)

    logger.info("Script execution complete! All original figures have been successfully generated in the results folder.")


if __name__ == "__main__":
    plt.style.use('seaborn-v0_8-whitegrid')
    main()